Repository deepsense-ai/db-ally, pull requests merged in 2024-07, with the labels that each got.

#66 refactor(prompts): prompt templates
  benchmark/dbally_benchmark/e2e_benchmark.py
  benchmark/dbally_benchmark/iql_benchmark.py
  benchmark/dbally_benchmark/text2sql/prompt_template.py
  docs/about/roadmap.md
  docs/how-to/llms/custom.md
  docs/how-to/views/few-shots.md
  docs/reference/collection.md
  docs/reference/index.md
  docs/reference/iql/iql_generator.md
  docs/reference/nl_responder.md
  docs/reference/prompt.md
  docs/reference/view_selection/llm_view_selector.md
  examples/recruiting.py
  examples/recruiting/views.py
  mkdocs.yml
  src/dbally/assistants/openai.py
  src/dbally/audit/events.py
  src/dbally/gradio/gradio_interface.py
  src/dbally/iql/_query.py
  src/dbally/iql_generator/iql_generator.py
  src/dbally/iql_generator/iql_prompt_template.py
  src/dbally/iql_generator/prompt.py
  src/dbally/llms/base.py
  src/dbally/llms/clients/base.py
  src/dbally/llms/clients/litellm.py
  src/dbally/llms/litellm.py
  src/dbally/nl_responder/nl_responder.py
  src/dbally/nl_responder/nl_responder_prompt_template.py
  src/dbally/nl_responder/prompts.py
  src/dbally/nl_responder/query_explainer_prompt_template.py
  src/dbally/prompt/__init__.py
  src/dbally/prompt/elements.py
  src/dbally/prompt/template.py
  src/dbally/prompts/__init__.py
  src/dbally/prompts/common_validation_utils.py
  src/dbally/prompts/formatters.py
  src/dbally/prompts/prompt_template.py
  src/dbally/view_selection/llm_view_selector.py
  src/dbally/view_selection/prompt.py
  src/dbally/view_selection/view_selector_prompt_template.py
  src/dbally/views/base.py
  src/dbally/views/freeform/text2sql/prompt.py
  src/dbally/views/freeform/text2sql/view.py
  src/dbally/views/structured.py
  src/dbally_codegen/autodiscovery.py
  tests/integration/test_llm_options.py
  tests/unit/mocks.py
  tests/unit/test_assistants_adapters.py
  tests/unit/test_collection.py
  tests/unit/test_fewshot.py
  tests/unit/test_iql_format.py
  tests/unit/test_iql_generator.py
  tests/unit/test_prompt_builder.py
  tests/unit/test_view_selector.py
Labels: refactor

#61 feat: add support for HuggingFace models loaded locally
  benchmark/dbally_benchmark/e2e_benchmark.py
  benchmark/dbally_benchmark/iql_benchmark.py
  benchmark/dbally_benchmark/text2sql_benchmark.py
  docs/how-to/llms/local.md
  docs/reference/llms/local.md
  mkdocs.yml
  setup.cfg
  src/dbally/llms/clients/local.py
  src/dbally/llms/local.py
Labels: feature

#68 fix: Prevent halucination when no data is returned
  src/dbally/nl_responder/prompts.py
Labels: fix

#70 feat: Add OpenTelemetry event handler
  docs/assets/otel_handler_jeager.png
  docs/how-to/trace_runs_with_otel.md
  docs/reference/event_handlers/otel_handler.md
  mkdocs.yml
  setup.cfg
  src/dbally/audit/__init__.py
  src/dbally/audit/event_handlers/otel_event_handler.py
  tests/unit/audit/__init__.py
  tests/unit/audit/event_handlers/__init__.py
  tests/unit/audit/event_handlers/test_otel_event_handler.py
Labels: feature

#73 refactor(iql): errors definition
  src/dbally/iql/_exceptions.py
  src/dbally/iql/_processor.py
  src/dbally/iql/_query.py
  src/dbally/iql_generator/iql_generator.py
  src/dbally/views/structured.py
  tests/integration/test_llm_options.py
  tests/unit/iql/test_iql_parser.py
  tests/unit/test_iql_generator.py
Labels: refactor

#59 feat: collection hierarchy
  docs/concepts/collections.md
  examples/recruiting/candidate_view_with_similarity_store.py
  examples/recruiting/candidates_freeform.py
  examples/recruiting/views.py
  examples/visualize_fallback_code.py
  src/dbally/__init__.py
  src/dbally/audit/event_handlers/cli_event_handler.py
  src/dbally/audit/event_handlers/otel_event_handler.py
  src/dbally/audit/events.py
  src/dbally/collection/collection.py
  src/dbally/gradio/gradio_interface.py
  tests/unit/test_fallback_collection.py
Labels: feature

#77 refactor(iql): add iql gen exception
  src/dbally/iql_generator/iql_generator.py
  src/dbally/llms/base.py
  src/dbally/nl_responder/nl_responder.py
  src/dbally/view_selection/llm_view_selector.py
  src/dbally/views/exceptions.py
  src/dbally/views/structured.py
Labels: refactor
