Repository deepsense-ai/db-ally, pull requests merged in 2024-08, with the labels that each got.

#80 fix(license): add CNRI Python License to whitelist
  .license-whitelist.txt
Labels: fix

#78 feat(views): optional filtering for structured views
  src/dbally/iql/_exceptions.py
  src/dbally/iql/_processor.py
  src/dbally/iql_generator/iql_generator.py
  src/dbally/iql_generator/prompt.py
  src/dbally/views/pandas_base.py
  src/dbally/views/sqlalchemy_base.py
  src/dbally/views/structured.py
  tests/unit/iql/test_iql_parser.py
  tests/unit/mocks.py
  tests/unit/test_iql_generator.py
Labels: feature

#79 feat(extra): prompt tuning
  benchmarks/README.md
  extra/README.md
  extra/prompt_tuning/README.md
  extra/prompt_tuning/config/config.yaml
  extra/prompt_tuning/config/data/superhero.yaml
  extra/prompt_tuning/config/llm/claude-3-haiku.yaml
  extra/prompt_tuning/config/llm/claude-3-opus.yaml
  extra/prompt_tuning/config/llm/claude-3.5-sonnet.yaml
  extra/prompt_tuning/config/llm/gpt-3.5-turbo.yaml
  extra/prompt_tuning/config/llm/gpt-4-turbo.yaml
  extra/prompt_tuning/config/llm/gpt-4o.yaml
  extra/prompt_tuning/config/program/filtering-assessor-baseline.yaml
  extra/prompt_tuning/config/program/filtering-assessor-cot.yaml
  extra/prompt_tuning/evaluate.py
  extra/prompt_tuning/tuning/__init__.py
  extra/prompt_tuning/tuning/loaders.py
  extra/prompt_tuning/tuning/metrics/__init__.py
  extra/prompt_tuning/tuning/metrics/iql.py
  extra/prompt_tuning/tuning/programs/__init__.py
  extra/prompt_tuning/tuning/programs/iql.py
  extra/prompt_tuning/tuning/signatures/__init__.py
  extra/prompt_tuning/tuning/signatures/iql.py
  extra/prompt_tuning/tuning/utils.py
  setup.cfg
Labels: feature

#86 docs: update logo
  README.md
  docs/assets/banner-dark.svg
  docs/assets/banner-light.svg
  docs/assets/favicon.ico
  docs/assets/guide_dog_lg.png
  docs/assets/guide_dog_sm.png
  docs/assets/logo.svg
  docs/index.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: docs

#62 feat: aggregations in structured views
  benchmarks/sql/bench/pipelines/base.py
  benchmarks/sql/bench/pipelines/collection.py
  benchmarks/sql/bench/pipelines/view.py
  benchmarks/sql/bench/views/structured/superhero.py
  docs/how-to/views/custom_views_code.py
  docs/quickstart/quickstart_code.py
  src/dbally/iql/__init__.py
  src/dbally/iql/_processor.py
  src/dbally/iql/_query.py
  src/dbally/iql_generator/iql_generator.py
  src/dbally/iql_generator/prompt.py
  src/dbally/prompt/template.py
  src/dbally/view_selection/prompt.py
  src/dbally/views/decorators.py
  src/dbally/views/exceptions.py
  src/dbally/views/methods_base.py
  src/dbally/views/pandas_base.py
  src/dbally/views/sqlalchemy_base.py
  src/dbally/views/structured.py
  tests/integration/test_llm_options.py
  tests/unit/iql/test_iql_parser.py
  tests/unit/mocks.py
  tests/unit/similarity/sample_module/submodule.py
  tests/unit/test_collection.py
  tests/unit/test_iql_format.py
  tests/unit/test_iql_generator.py
  tests/unit/views/test_methods_base.py
  tests/unit/views/test_pandas_base.py
  tests/unit/views/test_sqlalchemy_base.py
Labels: feature

#88 docs(quickstart): update quickstart
  docs/concepts/similarity_indexes.md
  docs/how-to/update_similarity_indexes.md
  docs/how-to/use_custom_similarity_fetcher.md
  docs/how-to/use_custom_similarity_store.md
  docs/quickstart/index.md
  docs/quickstart/multiple-views.md
  docs/quickstart/semantic-similarity.md
  docs/reference/similarity/index.md
  examples/intro.py
  examples/multiple_views.py
  examples/semantic_similarity.py
  mkdocs.yml
Labels: docs
